#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &
wmname LG3D &

bspc monitor eDP-1 -n center
bspc monitor HDMI-1 -n right

bspc monitor center -d 1 2 3 4 5 6 7 8
bspc monitor right -d 9 10

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#3c3836"
bspc config active_border_coloe "#3c3836"
bspc config focused_border_color "#FFFFFF"
bspc config presel_feedback_color "#ebdbb2"

bspc rule -a Brave-browser desktop='^3' follow=on focus=on 
bspc rule -a Firefox desktop='^3' follow=on focus=on

bspc rule -a Caja desktop='^4' state=tiled follow=on focus=on
bspc rule -a Thunar desktop='^4' state=floating follow=on focus=on

bspc rule -a Spotify desktoop='^5' state=tiled
bspc rule -a Pavucontrol desktop='^6' state=floating follow=on focus=on

bspc rule -a discord desktop='^7' follow=on focus=on
# set wallpaper
feh --bg-scale ~/Pictures/wallpapers/daemon.jpg &

# launch polybar
~/.config/polybar/./launch.sh

# piccom
picom --experimental-backends &
dunst &
